#If for some reason you want to disable this plugin, just set this to 'false'. Default: true
enable-plugin: true

language: english

#If 'true', the 'mail-cost' value will be multiplied by the number of items inside the mailbox. Default: true
cost-per-item: true

#Cost to send items to another players. Default: 1.50 (per item), 30.0 (per mailbox)
mail-cost: 1.50

#Should administrators be warned about new updates? Default: true
#If 'true', this will not bother you while you are playing. I promisse!
update:
    check: true
    #download: true # Work in progress feature!

#Do not change this under any circumstances!
config-version: 4