name: LTItemMail
description: A new way of sending items to another player without need teleporting to them.
version: 0.2.7
api-version: 1.13
load: STARTUP
author: [leothawne]
website: https://leothawne.github.io/LTItemMail/
url: https://leothawne.github.io/LTItemMail/
main: io.github.leothawne.LTItemMail.LTItemMail
database: true
soft-depend: [Vault, Essentials]
commands:
    itemmail:
        description: Shows commands for everyone.
        aliases: [ima]
        usage: /<command>
    mailitem:
        description: Open a mailbox to put items inside.
        aliases: [mit, enviaritem, vit]
        usage: /<command>
    itemmailadmin:
        description: Shows commands for administrators.
        aliases: [imad]
        usage: /<command>
permissions:
    LTItemMail.use:
        description: Gives access to players' commands.
        default: true
    LTItemMail.send:
        description: Allows players to send mailboxes.
        default: true
    LTItemMail.admin:
        description: Gives access to admins' commands.
        default: op