name: LTItemMail
description: A new way of sending items to another players in Minecraft.
version: 0.2.4
api-version: 1.13
load: POSTWORLD
author: [leothawne]
website: https://leothawne.github.io/LTItemMail/
url: https://leothawne.github.io/LTItemMail/
main: io.github.leothawne.LTItemMail.LTItemMail
database: false
soft-depend: [Vault]
commands:
    itemmail:
        description: All available commands for LT Item Mail.
        aliases: [ima]
        usage: /<command>
    sendbox:
        description: Instantly send items to other players.
        aliases: [sbx]
        usage: /<command>
    itemmailadmin:
        description: All admin commands for LT Item Mail.
        aliases: [imad]
        usage: /<command>
permissions:
    LTItemMail.use:
        description: Allow players to use LTIM commands.
        default: true
    LTItemMail.send:
        description: Allow players to send items to other players.
        default: true
    LTItemMail.admin:
        description: Allow admins to use LTIM admin commands.
        default: op