#Do not touch it!
config-version: 16
version-number: ${project.version}
build-number: ${v}
plugin:
  #Enable or disable LTItemMail. Default: true
  #
  #Habilita ou desabilita o LTItemMail. Padrão: true
  enable: true
  #Pre-installed languages support: portuguese, english, vietnamese. Default: english
  #
  #Suporte de idiomas pré-instalados: portuguese, english, vietnamese. Padrão: english
  #Para pt-BR, selecione: portuguese
  language: 'english'
  #Here you can customize the plugin tag that appears in chat. Default: [LTIM]
  #
  #Aqui você pode customizar a tag do plugin que aparece no chat. Padrão: [LTIM]
  tag: '&6[LTIM]'
  #Choose if you want to use LTItemMail in your Bungee network.
  #
  #Escolha se quer usar o LTItemMail na sua rede Bungee.
  bungee-mode: false
  #Each server must have an unique identifier. Otherwise physical mailboxes will break.
  #If you change this value, you and your players will have to replace every existing mailbox block, no matter if bungee mode is enabled or not.
  #
  #Cada servidor deve ter um identificador único. Senão caixas de corrêio físicas irão quebrar.
  #Se você alterar esse valor, você e seus jogadores terão que substituir todos os blocos de caixa de correio existentes, não importa se o modo bungee está ativado ou não.
  bungee-server-id: 'server1'
  #Choose whether download the resource pack on every startup (it will update the current downloaded zip file as well). Default: false
  #
  #Escolha se quer baixar o pacote de recursos em cada inicialização (isso também irá atualizar o arquivo zip baixado atualmente). Padrão: false
  resource-pack-download: false
  #For debug purposes only. Default: false
  #
  #Somente para fins de depuração. Padrão: false
  debug: false
database:
  #'flatfile' or 'mysql'
  #
  #'flatfile' ou 'mysql'
  type: 'flatfile'
  #Imports data from the old storage type to the new one.
  #
  #Importa os dados do tipo de armazenamento anterior para o novo.
  convert: false
  flatfile:
    #Do not change it unless you have manually changed the name of the database file.
    #
    #Não mude a menos que tenha mudado manualmente o nome do arquivo banco de dados.
    file: 'mailboxes.db'
  #You can use my plugin in bungee mode as long as it is installed on every server you want to use (except proxy).
  #And you must use the same MySQL database.
  #Remember to set bungee-mode 'true'.
  #
  #Você pode usar meu plugin no modo Bungee desde que ele esteja instalado em todos os servidores que você irá utilizá-lo (exceto na proxy).
  #E o mesmo banco de dados MySQL deve estar sendo usado.
  #Lembre-se de definir bungee-mode 'true'.
  mysql:
    host: '127.0.0.1:3306'
    user: 'root'
    password: ''
    database: 'ltitemmail'
hook:
  #Set 'true' if you wish to use economy plugins (set the mail price).
  #
  #Defina 'true' se desejar usar um plugin de economia (defina o preço do corrêio).
  economy:
    enable: false
    #Compatible plugins: Vault for economies in general, CoinsEngine (ex: CoinsEngine:Coins) or The New Economy (ex: TheNewEconomy:USD). Default: Vault
    #
    #Plugins compatíveis: Vault para economias em geral, CoinsEngine (ex: CoinsEngine:Moedas) ou The New Economy (ex: TheNewEconomy:USD). Padrão: Vault
    type: 'Vault'
  #Set 'true' if you wish to show mailbox blocks on the map.
  #
  #Defina 'true' se desejar mostrar blocos de caixa de corrêio no mapa.
  dynmap: false
  #Set 'true' if you wish to show mailbox blocks on the map.
  #
  #Defina 'true' se desejar mostrar blocos de caixa de corrêio no mapa.
  bluemap: false
  #Set 'true' if you wish to show holograms above mailbox blocks.
  #
  #Defina 'true' se desejar mostrar hologramas acima do blocos de caixa de corrêio.
  decentholograms: true
  #My plugin has an in-built protection for mailbox blocks, but you can use some extra protection with the plugins listed below:
  #
  #Meu plugin tem uma proteção imbutida para blocos de caixa de corrêio, mas você pode usar uma proteção extra com os plugins abaixo:
  griefprevention: false
  redprotect: false
  towny: false
  worldguard: false
  #Useful for TOAST notifications (refer to "mail.display" below).
  #
  #Útil para notificações TOAST (consulte "mail.display" abaixo).
  ultimateadvancementapi: false
  #You can replace mail buttons with custom heads from HeadDatabase.
  #
  #Você pode substituir botões do corrêio com cabeças customizadas do HeadDatabase.
  headdatabase: false
mail:
  #When a new mail arrives, how do you want the message to appear? Valid: CHAT, TITLE, TOAST. Default: CHAT
  #
  #Quando chegar um novo corrêio, como deseja mostrar a mensagem? Válido: CHAT, TITLE, TOAST. Padrão: CHAT
  display: 'CHAT'
  #If you are using the LT Item Mail Resource Pack, set this to 'true'. Default: false
  #
  #Se você estiver usando o LT Item Mail Resource Pack, mude isso para 'true'. Padrão: false
  textures: false
  cost:
    #Set 'true' to multiply the price by the number of items. Default: false
    #
    #Defina 'true' para multiplicar o preço pelo número de itens. Padrão: false
    per-item: false
    #Price to send items. Default: 1.5 (per item) and 30.0 (per mail)
    #
    #Preço para enviar itens. Padrão: 1.5 (por item) e 30.0 (por corrêio)
    value: 30.0
  #Name of the mail inventory. Default: Mail
  #
  #Nome do inventário de corrêio. Padrão: Mail
  name: '&3&lMailbox&r&4'
autorun:
  mail:
    new:
      on-close: []
    pending:
      on-close:
        - 'PLAYER:/itemmail list'
    claimed:
      on-close:
        - 'PLAYER:/itemmail list'
#Should administrators be warned about new updates? Default: true
#
#Os administratores devem ser notificados sobre novas atualizações? Padrão: true
update:
  check: true
  periodic-notification: true
  automatic: true
boards:
  console-only: false