name: ${project.name}
description: ${project.description}
version: ${project.version}
build: ${buildNumber}
api-version: 1.17
load: POSTWORLD
authors:
  - Nobookie
  - leothawne
website: ${project.url}
main: ${project.groupId}.${project.artifactId}.${project.name}
database: true
softdepend:
  - Vault
  - WorldGuard
  - GriefPrevention
  - RedProtect
  - Towny
  - dynmap
  - BlueMap
  - DecentHolograms
  - PlaceholderAPI
  - CoinsEngine
  - UltimateAdvancementAPI
  - TheNewEconomy
  - PlugMan
  - PlugManX
  - HeadDatabase
  - Skulls
  - Citizens