name: LTItemMail
description: Have you ever imagined mailing items to your friends in Minecraft?
version: ${project.version}
api-version: 1.13
load: POSTWORLD
author: [leothawne]
website: https://leothawne.github.io/LTItemMail/
url: https://leothawne.github.io/LTItemMail/
main: io.github.leothawne.LTItemMail.LTItemMail
database: true
soft-depend: [Vault]
commands:
    itemmail:
        description: Commands for players.
        aliases: [ima, imail]
        usage: /<command>
    mailitem:
        description: Command for players.
        aliases: [mit, enviaritem, mail]
        usage: /<command>
    itemmailadmin:
        description: Commands for admins.
        aliases: [imad, imadmin]
        usage: /<command>
permissions:
    ltitemmail.player:
        default: true
    ltitemmail.player.version:
        default: true
    ltitemmail.player.list:
        default: true
    ltitemmail.player.open:
        default: true
    ltitemmail.player.delete:
        default: true
    ltitemmail.player.send:
        default: true
    ltitemmail.player.notify:
        default: true
    ltitemmail.block.place:
        default: true
    ltitemmail.block.break:
        default: true
    ltitemmail.block.use:
        default: true
    ltitemmail.admin:
        default: op
    ltitemmail.admin.update:
        default: op
    ltitemmail.admin.list:
        default: op
    ltitemmail.admin.recover:
        default: op
    ltitemmail.admin.notify:
        default: op
    ltitemmail.block.break-bypass:
        default: op
    ltitemmail.admin.bypass:
        default: false