name: ${project.name}
description: ${project.description}
version: ${project.version}
build: ${v}
api-version: 1.14
load: POSTWORLD
authors: [Nobookie, leothawne]
website: https://www.spigotmc.org/resources/62294/
main: ${project.groupId}.${project.artifactId}.${project.name}
database: true
softdepend:
  - Vault
  - WorldGuard
  - GriefPrevention
  - RedProtect
  - Towny
  - dynmap
  - BlueMap
  - DecentHolograms
  - PlaceholderAPI
  - CoinsEngine
  - UltimateAdvancementAPI
  - TheNewEconomy