name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: "1.14"
load: POSTWORLD
author: leothawne
website: https://leothawne.github.io/LTItemMail/
url: https://leothawne.github.io/LTItemMail/
main: ${project.groupId}.${project.artifactId}.${project.name}
database: true
softdepend: [Vault, Essentials, GriefPrevention, RedProtect, Towny, WorldGuard]
commands:
    itemmail:
        description: Used to send items and to check your mailbox.
        aliases: [ima, imail]
        usage: /<command>
    mailitem:
        description: Used to send items.
        aliases: [mit, enviaritem, mail]
        usage: /<command>
    itemmailadmin:
        description: For administration purposes.
        aliases: [imad, imadmin]
        usage: /<command>
permissions:
    ltitemmail.player.all:
        default: true
        children:
            ltitemmail.player: true
            ltitemmail.player.version: true
            ltitemmail.player.list: true
            ltitemmail.player.open: true
            ltitemmail.player.delete: true
            ltitemmail.player.send: true
            ltitemmail.player.info: true
            ltitemmail.player.notify: true
            ltitemmail.block.place: true
            ltitemmail.block.break: true
            ltitemmail.block.use: true
    ltitemmail.admin.all:
        default: op
        children:
           ltitemmail.admin: true
           ltitemmail.admin.update: true
           ltitemmail.admin.list: true
           ltitemmail.admin.recover: true
           ltitemmail.admin.reload: true
           ltitemmail.admin.notify: true
           ltitemmail.admin.ban: true
           ltitemmail.admin.unban: true
           ltitemmail.block.break-bypass: true
    ltitemmail.player:
        default: true
    ltitemmail.player.version:
        default: true
    ltitemmail.player.list:
        default: true
    ltitemmail.player.open:
        default: true
    ltitemmail.player.delete:
        default: true
    ltitemmail.player.send:
        default: true
    ltitemmail.player.info:
        default: true
    ltitemmail.player.notify:
        default: true
    ltitemmail.block.place:
        default: true
    ltitemmail.block.break:
        default: true
    ltitemmail.block.use:
        default: true
    ltitemmail.admin:
        default: op
    ltitemmail.admin.update:
        default: op
    ltitemmail.admin.list:
        default: op
    ltitemmail.admin.recover:
        default: op
    ltitemmail.admin.reload:
        default: op
    ltitemmail.admin.notify:
        default: op
    ltitemmail.admin.ban:
        default: op
    ltitemmail.admin.unban:
        default: op
    ltitemmail.block.break-bypass:
        default: op
    ltitemmail.admin.bypass:
        default: false