main:
    enabled: false
    warnings:
        - Estou desabilitando para fazer um teste.
boards:
    0:
        title: Teste 1
        contents:
            - teste 1
            - teste 1
            - teste 1
    1:
        title: Teste 2
        contents:
            - teste 2
            - teste 2
            - teste 2
    2:
        title: Teste 3
        contents:
            - teste 3
            - teste 3
            - teste 3
