main:
    enabled: true
    warnings: []
boards:
    0:
        title: '1# Teste 1'
        contents:
            - 'teste 1'
            - 'teste 1'
            - 'teste 1'
    1:
        title: '2# Teste 2'
        contents:
            - 'teste 2'
            - 'teste 2'
            - 'teste 2'
    2:
        title: '3# Teste 3'
        contents:
            - 'teste 3'
            - 'teste 3'
            - 'teste 3'
